#!/usr/bin/env bash

function detect_container_command() {


if [ -z "${DEFAULT_CONTAINER_CMD}" ]; then
	DEFAULT_CONTAINER_CMD="$(podman version > /dev/null 2>&1 && echo podman)"
fi
if [ -z "${DEFAULT_CONTAINER_CMD}" ]; then
	DEFAULT_CONTAINER_CMD="$(docker version > /dev/null 2>&1 && echo docker)"
fi
CONTAINER_CMD="${DEFAULT_CONTAINER_CMD}"
}



# default values for ccommand line options:
#
#DEFAULT_CONTAINER_CMD=""
DEFAULT_LANG="c"
LANG="${DEFAULT_LANG}"
DEFAULT_REGISTRY="quay.io"
REGISTRY="${DEFAULT_REGISTRY}"
CONTAINER_CMD=""
DEFAULT_OS=fedora
OS="${DEFAULT_OS}"
DEFAULT_NAMESPACE="buildbox"
NAMESPACE="${DEFAULT_NAMESPACE}"
BUILD_CMD=""
DEPS=""
DEFAULT_ACTION="help"
ACTION="${DEFAULT_ACTION}"
# action that was explicitly set from the command line:
SELECTED_ACTION=""
 ACTION="${DEFAULT_ACTION}"
 # shell for interactive use:
 DEFAULT_I_SHELL="bash"
 I_SHELL="${DEFAULT_I_SHELL}"


detect_container_command

if [ -z "${DEFAULT_CONTAINER_CMD}" ]; then
    echo "error: failed to detect container command (podman or docker)."
    exit 1
fi

function usage() {
>&2 cat <<EOF

builbo: build software projects in buildbox containers.

USAGE: builbo  options

These are the supported options:
[ -l | --lang (c|latex) ]                    - compilation language (default: ${DEFAULT_LANG})
[ -r | --registry (quay.io|... ]             - container registry (default: ${DEFAULT_REGISTRY})
[ -c | --container-cmd (podman|docker) ]     - default: ${DEFAULT_CONTAINER_CMD} (auto-detected)
[ -o | --os (fedora|debian|ubuntu|rocky|suse) ]         - linux distro (default: ${DEFAULT_OS})
[ -n | --registry-namespace (...) ]          - default: ${DEFAULT_NAMESPACE}
[ -s  | --build-script (command|path) ]              - command or local script (in the CWD)  for building the project.
[ -d | --deps (pkg,pkg,pkg,...) ]            - additional packages to install (comma-separated)
[  -i | --shell (bash) ]                      - interactive shell (default: ${DEFAULT_I_SHELL})
[ -h | --help ]                              - action help: print this usage information
[-t | --test ]                               - action test: print some diagnostic info for  testing this program
[ -b | --build ]                             - action build: perform a build in the CWD
[ -e | --enter]                              - action enter: enter container in interactive mode (shell)


The Options -l, -r, -o, and -n in combination determine the  buildbox image (by tag) to be used.


The options -h, -t, -e, and -b are the available actions (help, test, enter, and build) to be performed.

Exactly one of the actions  must be selected.

The build action requires the additional option -s.
The enter action  makes use of the --shell option.

EOF

}

function set_action() {

local action="$1"

if [ -n "${SELECTED_ACTION}" ]; then
        echo "Error: multiple actions specified on cmdline but only one is allowed."
        usage
        exit 1
    fi



	echo "selecting action '${action}'"
	ACTION="${action}"
	SELECTED_ACTION="${action}"

}




# parsing command line arguments (portable: works on stock macOS without GNU getopt):
# We support GNU-style long options by translating them to short options first,
# then using POSIX getopts.

echo " processing command line arguments.."

rewrite_args=()
while [ $# -gt 0 ]; do
  case "$1" in
    --lang)
      if [ $# -lt 2 ] || [[ "$2" == -* ]]; then
        echo "error: option '$1' requires a value." >&2
        usage
        exit 1
      fi
      rewrite_args+=("-l" "$2"); shift 2 ;;
    --lang=*)           rewrite_args+=("-l" "${1#*=}"); shift ;;
    --registry)
      if [ $# -lt 2 ] || [[ "$2" == -* ]]; then
        echo "error: option '$1' requires a value." >&2
        usage
        exit 1
      fi
      rewrite_args+=("-r" "$2"); shift 2 ;;
    --registry=*)       rewrite_args+=("-r" "${1#*=}"); shift ;;
    --container-cmd)
      if [ $# -lt 2 ] || [[ "$2" == -* ]]; then
        echo "error: option '$1' requires a value." >&2
        usage
        exit 1
      fi
      rewrite_args+=("-c" "$2"); shift 2 ;;
    --container-cmd=*)  rewrite_args+=("-c" "${1#*=}"); shift ;;
    --os)
      if [ $# -lt 2 ] || [[ "$2" == -* ]]; then
        echo "error: option '$1' requires a value." >&2
        usage
        exit 1
      fi
      rewrite_args+=("-o" "$2"); shift 2 ;;
    --os=*)             rewrite_args+=("-o" "${1#*=}"); shift ;;
    --registry-namespace)
      if [ $# -lt 2 ] || [[ "$2" == -* ]]; then
        echo "error: option '$1' requires a value." >&2
        usage
        exit 1
      fi
      rewrite_args+=("-n" "$2"); shift 2 ;;
    --registry-namespace=*) rewrite_args+=("-n" "${1#*=}"); shift ;;
    --build-script)
      if [ $# -lt 2 ] || [[ "$2" == -* ]]; then
        echo "error: option '$1' requires a value." >&2
        usage
        exit 1
      fi
      rewrite_args+=("-s" "$2"); shift 2 ;;
    --build-script=*)   rewrite_args+=("-s" "${1#*=}"); shift ;;
    --deps)
      if [ $# -lt 2 ] || [[ "$2" == -* ]]; then
        echo "error: option '$1' requires a value." >&2
        usage
        exit 1
      fi
      rewrite_args+=("-d" "$2"); shift 2 ;;
    --deps=*)           rewrite_args+=("-d" "${1#*=}"); shift ;;
    --shell)
      if [ $# -lt 2 ] || [[ "$2" == -* ]]; then
        echo "error: option '$1' requires a value." >&2
        usage
        exit 1
      fi
      rewrite_args+=("-i" "$2"); shift 2 ;;
    --shell=*)          rewrite_args+=("-i" "${1#*=}"); shift ;;
    --help)             rewrite_args+=("-h"); shift ;;
    --test)             rewrite_args+=("-t"); shift ;;
    --build)            rewrite_args+=("-b"); shift ;;
    --enter)            rewrite_args+=("-e"); shift ;;
    --)                 rewrite_args+=("--"); shift; break ;;
    --*)
      echo "error: unknown option '$1'." >&2
      usage
      exit 1
      ;;
    -*)                 rewrite_args+=("$1"); shift ;;
    *)                  break ;;
  esac
done

# append any remaining positional args unchanged
while [ $# -gt 0 ]; do
  rewrite_args+=("$1")
  shift
done

set -- "${rewrite_args[@]}"

# l=lang r=registry c=container-cmd o=os n=registry-namespace s=build-script d=deps i=shell h=help b=build t=test e=enter
optstring=":l:r:c:o:n:s:d:i:hbte"
OPTIND=1

while getopts "${optstring}" opt; do
  case "${opt}" in
    l) LANG="${OPTARG}"; echo "language '${LANG}' specified." ;;
    r) REGISTRY="${OPTARG}"; echo "registry '${REGISTRY}' specified." ;;
    c) CONTAINER_CMD="${OPTARG}"; echo "container command '${CONTAINER_CMD}' specified." ;;
    o) OS="${OPTARG}"; echo "operating system '${OS}' specified." ;;
    n) NAMESPACE="${OPTARG}"; echo "namespace '${NAMESPACE}' specified." ;;
    s) BUILD_CMD="${OPTARG}"; echo "build command '${BUILD_CMD}' specified." ;;
    d) DEPS="${OPTARG}"; echo "dependencies '${DEPS}' specified." ;;
    i) I_SHELL="${OPTARG}"; echo "interactive shell '${I_SHELL}' specified." ;;
    h) set_action "help"; echo "action help specified." ;;
    b) set_action "build"; echo "action build specified." ;;
    t) set_action "test"; echo "action test specified." ;;
    e) set_action "enter"; echo "action enter specified." ;;
    :)
      echo "error: invalid args." >&2
      usage
      exit 1
      ;;
    \?)
      echo "error: invalid args." >&2
      usage
      exit 1
      ;;
  esac
done
shift $((OPTIND-1))

echo "done processing arguments."

#post-processing args





if [ -z "$CONTAINER_CMD" ]; then
    echo "error: container command not set. Please use '-c command'."
    usage
    exit 1
fi

DEPS_PKGS="${DEPS//,/ }"
IMAGE="${REGISTRY}/${NAMESPACE}/buildbox/${OS}-${LANG}:latest"


case "${OS}" in

fedora)
    PKG_CMD="dnf install -y"
    ;;
debian|ubuntu)
    PKG_CMD="apt-get install --yes"
    ;;
suse)
    PKG_CMD="zypper install -y"
    ;;
esac






# setting CONTAINER_RUN_CMD assumes CONTAINER_RUN_CMD is set.
if [ -z "${CONTAINER_CMD}" ]; then
    echo "error: container command not set. this should not happen."
    exit 1
fi
if [ "$CONTAINER_CMD" = "podman" ]; then

    CONTAINER_RUN_CMD="${CONTAINER_CMD} run -it --workdir /work --mount type=bind,source=$(pwd),target=/work,relabel=private --platform linux/amd64 ${IMAGE}"
 elif [ "$CONTAINER_CMD" = "docker" ]; then
     CONTAINER_RUN_CMD="${CONTAINER_CMD} run --workdir /work -v $(pwd):/work --platform linux/amd64 ${IMAGE}"

fi


if [ "${ACTION}" = "build" ]; then


    if [ -z "${BUILD_CMD}" ]; then

        echo "error: action 'build' requires --build-script (-s)"
        usage
        exit 1
    fi


fi




function print_settings() {
  echo "settings:"
  echo
  echo "LANG: ${LANG}"
  echo "OS: ${OS}"
  echo "REGISTRY: ${REGISTRY}"
  echo "NAMESPACE: ${NAMESPACE}"
  echo "BUILD_CMD: ${BUILD_CMD}"
  echo "DEPS: ${DEPS}"
  echo "DEPS_PKGS: ${DEPS_PKGS}"
  echo "PKG_CMD: ${PKG_CMD}"
  echo "CONTAINER_CMD: ${CONTAINER_CMD}"
  echo "CONTAINER_RUN_CMD: '${CONTAINER_RUN_CMD}'"
  echo "interactive shell: '${I_SHELL}'"
  echo "IMAGE: ${IMAGE}"
    
}

if [ "$ACTION" = "test" ]; then
    echo "performing test action."
    print_settings
    exit 0
fi

if [ "${ACTION}" = "help" ]; then

    echo "performing help action."

    usage
    exit 0
fi
















function install_deps() {
    if [ -n "${DEPS}" ]; then
        ${CONTAINER_RUN_CMD}   bash -c "${PKG_CMD} ${DEPS_PKGS}"

    fi

}

function install_deps_and_run_build() {



    local CMD="${BUILD_CMD}"

    if [ -n "${DEPS}" ]; then
        CMD="${PKG_CMD} ${DEPS_PKGS} && ${BUILD_CMD}"

    fi

${CONTAINER_RUN_CMD} bash -c "${CMD}"
}

function enter_container() {

${CONTAINER_RUN_CMD} "${I_SHELL}"

}


if [ "${ACTION}" = "build" ]; then
echo "performing build action."
install_deps_and_run_build

elif [ "${ACTION}" = "enter" ]; then
   echo "performing enter action." 
    enter_container
fi






