#!/usr/bin/env bash

function detect_container_command() {


	if [ -z "${DEFAULT_CONTAINER_CMD}" ]; then
		DEFAULT_CONTAINER_CMD="$(podman version > /dev/null 2>&1 && echo podman)"
	fi
	if [ -z "${DEFAULT_CONTAINER_CMD}" ]; then
		DEFAULT_CONTAINER_CMD="$(docker version > /dev/null 2>&1 && echo docker)"
	fi
	CONTAINER_CMD="${DEFAULT_CONTAINER_CMD}"
}



# default values for ccommand line options:
#
#DEFAULT_CONTAINER_CMD=""
 DEFAULT_LANG="c"
 LANG="${DEFAULT_LANG}"
 DEFAULT_REGISTRY="quay.io"
 REGISTRY="${DEFAULT_REGISTRY}"
 CONTAINER_CMD=""
 DEFAULT_OS=fedora
 OS="${DEFAULT_OS}"
 DEFAULT_NAMESPACE="buildbox"
 NAMESPACE="${DEFAULT_NAMESPACE}"
 BUILD_CMD=""
 DEPS=""
 DEFAULT_ACTION="help"
 ACTION="${DEFAULT_ACTION}"
 # action that was explixitly set from the command line:
 SELECTED_ACTION=""
 ACTION="" 
 # shell for interactive use:
 DEFAULT_I_SHELL="bash"
 I_SHELL="${DEFAULT_I_SHELL}"


detect_container_command

if [ -z "${DEFAULT_CONTAINER_CMD}" ]; then
    echo "error: failed to detect container command (podman or docker)."
    exit 1
fi

function usage() {
>&2 cat <<EOF

builbo: build software projects in buildbox containers.

USAGE: builbo  options

These are the supported options:
[ -l | --lang (c|latex) ]                    - compilation language (default: ${DEFAULT_LANG})
[ -r | --registry (quay.io|... ]             - container registry (default: ${DEFAULT_REGISTRY})
[ -c | --container-cmd (podman|docker) ]     - default: ${DEFAULT_CONTAINER_CMD} (auto-detected)
[ -o | --os (fedora|debian|ubuntu|rocky|suse) ]         - linux distro (default: ${DEFAULT_OS})
[ -n | --registry-namespace (...) ]          - default: ${DEFAULT_NAMESPACE}
[ -s  | --build-script (command|path) ]              - command or local script (in the CWD)  for building the project.
[ -d | --deps (pkg,pkg,pkg,...) ]            - additional packages to install (comma-separated)
[  -i | --shell (bash) ]                      - interactive shell (default: ${DEFAULT_I_SHELL})
[ -h | --help ]                              - action help: print this usage information
[-t | --test ]                               - action test: print some diagnostic info for  testing this program
[ -b | --build ]                             - action build: perform a build in the CWD
[ -e | --enter]                              - action enter: enter container in interactive mode (shell)


The Options -l, -r, -o, and -n in combination determine the  buildbox image (by tag) to be used.


The options -h, -t, -e, and -b are the available actions (help, test, enter, and build) to be performed.

Exactly one of the actions  must be selected.

The build action requires the additional option -s.
The enter action  makes use of the --shell option.

EOF

}

function set_action() {

local action="$1"

if [ -n "${SELECTED_ACTION}" ]; then
        echo "Error: multiple actions specified on cmdline but only one is allowed."
        usage
        exit 1
    fi



	echo "selecting action '${action}'"
	ACTION="${action}"
	SELECTED_ACTION="${action}"

}




# parsing command line arguments:
optstring="l:r:c:o:n:hbtes:d:"
optstring_long="lang:,registry:,container-cmd:,help,test,build,enter,build-script:,deps:"


parsed_args=$(getopt  -n "builbo" -o "$optstring" -l "$optstring_long" -- "$@")
args_are_valid=$?

if [ "$args_are_valid" != "0" ]; then
  echo "error:invalid args."
  usage
  exit 1
fi

# processing parsed args

echo " processing command line arguments.."
eval set -- "${parsed_args}"
while :
do
arg="$1"
echo "processing argument '${arg}'."
case "${arg}" in
 -l | --lang)
	LANG="$2"
	echo "language '${LANG}' specified."
	shift 2
	;;
 -r  | --registry)
	REGISTRY="$2"
	echo "registry '${REGISTRY}' specified."

	shift 2
	;;
 -c | --container-cmd)
	CONTAINER_CMD="$2"
	echo "container command '${CONTAINER_CMD}' specified."
	shift 2
	;;
 -o | --os)
	OS="$2"
	echo "operating system '${OS}'specified."
	shift 2
	;;
 -n | --registry-namespace)
	NAMESPACE="$2"
	echo "namespace '${NAMESPACE}' specified."
	shift 2
	;;
 -s | --build-script)
	BUILD_CMD="$2"
	echo "build command '${BUILD_CMD}' specified."
	shift 2
	;;
 -d | --deps)
	DEPS="$2"
	echo "dependencies '${DEPS}' specified."
	shift 2
	;;
 -h | --help)
	set_action "help"
	echo "action help specified."
	shift
	;;
 -b| --build)
	echo "action build specified."
	set_action "build"
	echo 
	shift
	;;
 -t| --test)
	set_action "test"
	echo "action test specified."
	shift
	;;
 -e|--enter)
	set_action "enter"
	echo "action enter specified."
	shift
	;;


 # -- means end of args. ignore and stop processing.
 --)
 shift
 break
 ;;
 *)
	echo "Unexpected option $1. - this should not happen."
	# this should have been caught above with args_valid
	usage
	exit 1 
	;;
esac
done
echo "done processing arguments."

#post-processing args





if [ -z "$CONTAINER_CMD" ]; then
    echo "error: container command not set. Please use '-c command'."
    usage
    exit 1
fi

DEPS_PKGS="${DEPS//,/ }"
IMAGE="${REGISTRY}/${NAMESPACE}/buildbox/${OS}-${LANG}:latest"


case "${OS}" in

fedora)
    PKG_CMD="dnf install -y"
    ;;
debian|ubuntu)
    PKG_CMD="apt-get install --yes"
    ;;
suse)
    PKG_CMD="zypper install -y"
    ;;
esac






# setting CONTAINER_RUN_CMD assumes CONTAINER_RUN_CMD is set.
if [ -z "${CONTAINER_CMD}" ]; then
    echo "error: container command not set. this should not happen."
    exit 1
fi
if [ "$CONTAINER_CMD" = "podman" ]; then

    CONTAINER_RUN_CMD="${CONTAINER_CMD} run -it --workdir /work --mount type=bind,source=$(pwd),target=/work,relabel=private --platform linux/amd64 ${IMAGE}"
 elif [ "$CONTAINER_CMD" = "docker" ]; then
     CONTAINER_RUN_CMD="${CONTAINER_CMD} run --workdir /work -v $(pwd):/work --platform linux/amd64 ${IMAGE}"

fi


if [ "${ACTION}" = "build" ]; then


    if [ -z "${BUILD_CMD}" ]; then

        echo "error: action 'build' requires --build-script (-s)"
        usage
        exit 1
    fi


fi




function print_settings() {
  echo "settings:"
  echo
  echo "LANG: ${LANG}"
  echo "OS: ${OS}"
  echo "REGISTRY: ${REGISTRY}"
  echo "NAMESPACE: ${NAMESPACE}"
  echo "BUILD_CMD: ${BUILD_CMD}"
  echo "DEPS: ${DEPS}"
  echo "DEPS_PKGS: ${DEPS_PKGS}"
  echo "PKG_CMD: ${PKG_CMD}"
  echo "CONTAINER_CMD: ${CONTAINER_CMD}"
  echo "CONTAINER_RUN_CMD: '${CONTAINER_RUN_CMD}'"
  echo "interactive shell: '${I_SHELL}'"
  echo "IMAGE: ${IMAGE}"
    
}

if [ "$ACTION" = "test" ]; then
    echo "performing test action."
    print_settings
    exit 0
fi

if [ "${ACTION}" = "help" ]; then

    echo "performing help action."

    usage
    exit 0
fi
















function install_deps() {
    if [ -n "${DEPS}" ]; then
        ${CONTAINER_RUN_CMD}   bash -c "${PKG_CMD} ${DEPS_PKGS}"

    fi

}

function install_deps_and_run_build() {



    local CMD="${BUILD_CMD}"

    if [ -n "${DEPS}" ]; then
        CMD="${PKG_CMD} ${DEPS_PKGS} && ${BUILD_CMD}"

    fi

${CONTAINER_RUN_CMD} bash -c "${CMD}"
}

function enter_container() {

${CONTAINER_RUN_CMD} "${I_SHELL}"

}


if [ "${ACTION}" = "build" ]; then
echo "performing build action."
install_deps_and_run_build

elif [ "${ACTION}" = "enter" ]; then
   echo "performing enter action." 
    enter_container
fi






